services:
  client:
    build: .
    environment:
      MYSQL_PING_ATTEMPTS: "10"
      DATABASE_URL: mysql2://root@db/sakila
    volumes:
      - ./:/mnt
    depends_on:
      - db
  db:
    image: budougumi0617/mysql-sakila:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
