name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: budougumi0617/mysql-sakila:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "1"
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 1s --health-timeout 3s --health-retries 60
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.1
          - 3.2
          - 3.3
        gemfile:
          - gemfiles/ar61.gemfile
          - gemfiles/ar70.gemfile
          - gemfiles/ar71.gemfile
          - gemfiles/ar72.gemfile
          - gemfiles/ar80.gemfile
        exclude:
          - ruby: 3.1
            gemfile: gemfiles/ar80.gemfile
    env:
      DATABASE_URL: mysql2://root@127.0.0.1/sakila
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
